testingdjango/accounts/urls.py
from django.conf.urls import url
from . import views

app_name = 'accounts'

urlpatterns = [
    url(r'^signup/$', views.signup_view, name='signup'),
    url(r'^login/$', views.login_view, name='login'),
    url(r'^logout/$', views.logout_view, name='logout'),

]

testingdjango/articles/urls.py
from django.conf.urls import url
from . import views


app_name= 'article'

urlpatterns = [
    url(r'^$', views.article_list, name="list"),
    url(r'^create/$', views.article_create, name="create"),
    url(r'^(?P<slug>[\w-]+)/$', views.article_detail, name="detail"),
]

testingdjango/testingdjango/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.urls import path
from . import views
from django.contrib.staticfiles.urls import staticfiles_urlpatterns


urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^articles/', include('articles.urls')),
    url(r'^accounts/', include('accounts.urls')),
    url(r'^about/$', views.about),
    url(r'^$', views.homepage),
    url(r'^myPage/', views.myPage),
]


urlpatterns += staticfiles_urlpatterns()

testingdjango/accounts/models.py
from django.db import models

# Create your models here.

testingdjango/articles/models.py
from django.db import models
from django.contrib.auth.models import User


# Create your models here.
# capital for the first letter for the class/ model name is conventional
class Article(models.Model):
    """docstring for Article. Auto_now_add will automatically add the tiime and date"""
    title = models.CharField(max_length=100)
    slug = models.SlugField()
    body = models.TextField()
    date = models.DateTimeField(auto_now_add=True)
    author = models.ForeignKey(User, default=None, on_delete=False)
    # add in thumbnail later
    # add in author later
    # def __init__(self, arg):
    #     super(Article, self).__init__()
    #     self.arg = arg

    def __str__(self):
        return self.title

    def snippet(self):
        return self.body[:50] + '...'

testingdjango/articles/forms.py
from django import forms
from .import models

class CreateArticle(forms.ModelForm):
    """docstring for CreateArticle."""
    class Meta:
        model = models.Article
        fields = ['title','body','slug']

testingdjango/accounts/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from django.contrib.auth import login, logout

# Creation your views here.
def signup_view(request):
    if request.method == 'POST':
        form = UserCreationForm(request.POST)
        if form.is_valid():
            user=form.save()
            login(request, user)
            return redirect('article:list')
    else:
        form = UserCreationForm()
    return render(request, 'accounts/signup.html', {'form': form})

def login_view(request):
    if request.method == 'POST':
        form = AuthenticationForm(data=request.POST)
        if form.is_valid():
            user = form.get_user()
            login(request, user)
            if 'next' in request.POST:
                return redirect(request.POST.get('next'))
            else:
                return redirect('article:list')
    else:
        form = AuthenticationForm()
    return render(request, 'accounts/login.html', {'form': form})

def logout_view(request):
    if request.method == 'POST':
        logout(request)
        return redirect('article:list')

testingdjango/articles/views.py
from django.shortcuts import render, redirect
from .models import Article
from django.http import HttpResponse
from django.contrib.auth.decorators import login_required
from .import forms


# Create your views here.
def article_list(request):
    articles = Article.objects.all().order_by('date')
    return render(request, "articles/article_list.html", {'theArticles':articles})

def article_detail(request, slug):
    # return HttpResponse(slug)
    article = Article.objects.get(slug=slug)
    return render(request, 'articles/article_detail.html', {'article': article})

@login_required(login_url="/accounts/login/")
def article_create(request):
    if request.method == 'POST':
        form = forms.CreateArticle(request.POST, request.FILES)
        if form.is_valid():
            instance = form.save(commit=False)
            instance.author = request.user
            instance.save()
            return redirect('article:list')
    else:
        form = forms.CreateArticle()
        return render(request, 'articles/article_create.html', {'form':form})

testingdjango/testingdjango/views.py
# importing the HttpResponse module; when the user request a page, this will allow me to send something back
from django.http import HttpResponse
from django.shortcuts import render

# homepage function a request parameter/ object
def homepage(request):
    return render(request, "homepage.html")
# about function a request parameter/ object
def about(request):
    return render(request, "about.html")

def myPage(request):
    return render(request, "myPage.html")

testingdjango/accounts/templates/accounts/login.html
{% extends 'base_layout.html' %}

{% block content %}


  <div class="container-fluid background_image">
    <div class="container moveDown">
      <div class="card centerIt">
        <div class="card-body">
            <center><h2 class="card-title mb-0">Login</h2></center>
            <center>
              <div class="row changeColor">
                <form class="site-form" action="{% url 'accounts:login'%}" method="post">
                  {% csrf_token %}
                  {{form.as_p}}
                  {% if request.GET.next %}
                    <input type="hidden" name="next" value="{{request.GET.next}}">
                </form>
              </div>
              {% endif %}
              <button class="btn btn-primary" type="submit">Login</button>
            </center>
        </div>
      </div>
    </div>
  </div>


{% endblock%}

testingdjango/accounts/templates/accounts/signup.html
{% extends 'base_layout.html' %}

{% block content %}

  <div class="signupPage">


    <h1>Signup</h1>
    <form class="site-form" action="/accounts/signup/" method="post">
      {% csrf_token %}
      {{form}}
      <br>
      <!-- <input type="radio" name="" value="" required>I accept the terms and conditions -->
      <br>
      <button class="btn btn-primary" type="submit">Signup</button>
    </form>
  </div>




{% endblock%}

testingdjango/articles/templates/articles/article_create.html
{% extends 'base_layout.html' %}

{% block content %}

<div class="row bgimage">
  <div class="container-fluid">
    <div class="container">
      <h2>Start a discussion</h2>
      <form action="{% url 'article:create' %}" method="post">
        {% csrf_token %}
        {{form.as_p}}
        <input type="submit" name="" value="Create">
      </form>
    </div>
  </div>
</div>



{% endblock %}

testingdjango/articles/templates/articles/article_detail.html
{% extends 'base_layout.html' %}

{% block content %}
<div class="container-fluid background_img">

  <div class="container">
    <div class="card centerIt">
      <div class="card-body">
        <h2>{{article.title}}</h2>
          <p class="giveColor">{{article.body}}</p>
          <p>{{article.date}}</p>
          <p>@{{article.author}}</p>
      </div>
    </div>
  </div>

{% endblock %}

testingdjango/articles/templates/articles/article_list.html
{% extends 'base_layout.html' %}

{% block content %}
<!-- JUMBOTRON -->
<div class="jumbotron jumbotron-fluid">
  <div class="container">
    <h1 class="display-4">Your Stories <i> from others</h1>


    <p>Freely express yourself by sharing the meals you enjoy:)</p>
    <button class="btn btn-warning" id="logoutNow" type="button" name="button">
      <a href="{% url 'article:create' %}">Start a discussion</a>
    </button>
  </div>
</div>

<!-- ARTICLES -->
<div class="container-fluid backgroundimg">
  <div class="articles downMove">
    <div class="container">
    {% for article in theArticles%}
      <div class="row col-12">
        <h2>
          <a class="giveColor" href="{% url 'article:detail' slug=article.slug%}">{{article.title}}</a>
        </h2>
      </div>

      <p>{{article.snippet}}</p>
      <p>{{article.date}}</p>
      <p>@{{article.author}}</p>

      <hr>

    {% endfor %}
    </div>
  </div>
</div>
{% endblock %}

testingdjango/templates/about.html
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title>Homepage</title>
  </head>
  <body>
    <h1>This is the about page.</h1>
    <p>I like django</p>
  </body>
</html>

testingdjango/templates/base_layout.html
{% load static from staticfiles %}

<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <link rel="stylesheet" href="{% static 'styles.css' %}">
    <!-- <link rel="stylesheet" href="{{ STATIC_URL }} https://maxcdn.bootstrapcdn.com/bootstrap/3.4.0/css/bootstrap.min.css"> -->
    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="{{ STATIC_URL }} https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <!-- reference your copy Font Awesome here (from our CDN or by hosting yourself) -->
    <link rel="stylesheet" href="{{ STATIC_URL }} https://use.fontawesome.com/releases/v5.8.1/css/all.css" integrity="sha384-50oBUHEmvpQ+1lW4y57PTFmhCaXp0ML5d60M1M7uH2+nqUivzIebhndOJK28anvf" crossorigin="anonymous">


    <title>Articles</title>
    <style>
      .flex {
        display: flex;
      }

      .inline-block {
        display: inline-block;
      }
    </style>
  </head>

  <body>
    <nav class="navbar navbar-light bg-light">

      <ul class="nav nav-pills container-fluid flex">
        <li class="nav-item" style="flex: 1">
          <a class="navbar-brand" href="{% url 'article:list' %}">Logo</a>
        </li>
        <div>
          <li class="nav-item inline-block">
            <a href="{% url 'article:create' %}">
              <button class="btn btn-warning" id="logoutNow" type="button" name="button">
                Start a discussion
              </button>
            </a>
          </li>
          <form class="form-inline inline-block" action="{% url 'accounts:logout' %}" method="post">
            {% csrf_token %}
            <button class="btn btn-primary" type="submit">Logout</button>
          </form>
        </div>
      </ul>
    </nav>

    {% block content %}

    {% endblock %}

    </body>
</html>

testingdjango/templates/homepage.html
{% load static from staticfiles %}


<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">

    <!-- Bootstrap core CSS -->
    <link rel="stylesheet" href="{% static 'bootstrap.css' %}">
    <!-- Custom fonts for this template -->
    <!-- <link rel="stylesheet" href="{{ STATIC_URL }} https://maxcdn.bootstrapcdn.com/bootstrap/3.4.0/css/bootstrap.min.css"> -->
    <link rel="stylesheet" href="{% static 'coming-soon.css' %}">
    <link rel="stylesheet" href="{% static 'styles.css' %}">

    <title>Homepage</title>
  </head>
  <body>

  <div class="masthead">
    <div class="masthead-bg"></div>
    <div class="container h-100">
      <div class="row h-100">
        <div class="col-12 my-auto">
          <div class="masthead-content text-white py-5 py-md-0">
            <h1 class="mb-3">Vegan Blogging Site Coming Soon!</h1>
            <p class="mb-5">We're working hard to finish the development of this site. Our target launch date is
              <strong>December 2019</strong>!</p>
          </div>
        </div>
      </div>
    </div>
  </div>

  <div class="social-icons">
    <ul class="list-unstyled text-center mb-0">
      <li class="list-unstyled-item">
        <button type="button" class="btn btn-outline-primary">
          <a class="font" href="{% url 'accounts:signup' %}">signup</a>
        </button>
      </li>
      <li class="list-unstyled-item">
        <button type="button" class="btn btn-outline-primary">
          <a href="{% url 'accounts:login' %}">login</a>
        </button>
      </li>
    </ul>
  </div>

  <!-- Bootstrap core JavaScript -->
  <script src="{% static 'jquery.js' %} "></script>
  <script src="{% static 'bootstrap.bundle.js' %} "></script>

  <!-- Custom scripts for this template -->
  <script src="{% static 'coming-soon.js' %} "></script>

</body>
</html>

testingdjango/templates/myPage.html
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title>My Custom Page</title>
  </head>
  <body>
    <h1>I will add my notes here.</h1>
  </body>
</html>